class_name QueryStrings
extends RefCounted

const Tiles = preload("res://src/tools/shared/building_tile_ids.gd")

# the first strict upper bound greater than xbld selects the name index
const GENERAL_NAME_UPPER_BOUNDS := [
	Tiles.RUBBLE_FIRST,
	Tiles.RADIOACTIVE_WASTE,
	Tiles.TREE_FIRST,
	Tiles.SMALL_PARK,
	Tiles.POWER_LINE_FIRST,
	Tiles.FIRST_ROAD,
	Tiles.RAIL_FIRST,
	Tiles.TUNNEL_FIRST,
	Tiles.ROAD_POWER_CROSSING_1,
	Tiles.RAIL_POWER_CROSSING_1,
	Tiles.HIGHWAY_STRAIGHT_1,
	Tiles.SUSPENSION_BRIDGE_1,
	Tiles.RAISING_BRIDGE_TOWER,
	Tiles.POWER_BRIDGE,
	Tiles.ONRAMP_FIRST,
	Tiles.HIGHWAY_SLOPE_FIRST,
	Tiles.HIGHWAY_BRIDGE,
	Tiles.RAIL_SUBWAY_FIRST,
	Tiles.DEVELOPED_FIRST,
	Tiles.MIDDLE_CLASS_HOMES_1X1_1,
	Tiles.LUXURY_HOMES_1X1_1,
	Tiles.COMMERCIAL_1X1_FIRST,
]


# tile names by name index
const TILE_NAMES: Array[String] = [
	"Katzenjammers",
	"Rubble",
	"Radioactive Waste",
	"Trees",
	"Park",
	"Power Lines",
	"Road",
	"Railway",
	"Tunnel Entrance",
	"Road",
	"Railway",
	"Highway",
	"Suspension Bridge",
	"Bridge",
	"Power Lines",
	"Highway Entrance",
	"Highway",
	"Highway Bridge",
	"Subway to Rail",
	"Lower-class homes",
	"Middle-class homes",
	"Luxury Homes",
	"Gas Station",
	"Bed & Breakfast Inn",
	"Convience Store",
	"Gas Station",
	"Small office building",
	"Office building",
	"Warehouse",
	"Cassidy's Toy Store",
	"Warehouse",
	"Chemical Storage",
	"Warehouse",
	"Industrial substation",
	"Construction",
	"Construction",
	"Abandoned building",
	"Abandoned building",
	"Cheap apartments",
	"Apartments",
	"Apartments",
	"Nice Apartments",
	"Nice Apartments",
	"Condominium",
	"Condominium",
	"Condominium",
	"Shopping center",
	"Grocery story",
	"Office building",
	"Resort hotel",
	"Office building",
	"Office / Retail",
	"Office building",
	"Office building",
	"Office building",
	"Office building",
	"Warehouse",
	"Chemical processing",
	"Factory",
	"Factory",
	"Factory",
	"Factory",
	"Factory",
	"Factory",
	"Construction",
	"Construction",
	"Construction",
	"Construction",
	"Abandoned building",
	"Abandoned building",
	"Abandoned building",
	"Abandoned building",
	"Large apartment building",
	"Large apartment building",
	"Condominium",
	"Condominium",
	"Office park",
	"Office tower",
	"Mini-mall",
	"Theatre Square",
	"Drive-in theater",
	"Office tower",
	"Office tower",
	"Parking lot",
	"Historic office building",
	"Corporate headquarters",
	"Chemical processing",
	"Large factory",
	"Industrial thingamajig",
	"Factory",
	"Large warehouse",
	"Warehouse",
	"Construction",
	"Construction",
	"Abandoned building",
	"Abandoned building",
	"Hydroelectric power",
	"Hydroelectric power",
	"Wind power",
	"Natural gas power plant",
	"Oil power plant",
	"Nuclear power plant",
	"Solar power plant",
	"Microwave power plant",
	"Fusion power plant",
	"Coal power plant",
	"City Hall",
	"Hospital",
	"Police station",
	"Fire station",
	"Museum",
	"Park",
	"School",
	"Stadium",
	"Prison",
	"College",
	"Zoo",
	"Statue",
	"Water pump",
	"Runway",
	"Runway",
	"Pier",
	"Crane",
	"Control tower",
	"Control tower",
	"Warehouse",
	"Building",
	"Buiding",
	"Tarmac",
	"F-15b",
	"Hanger",
	"Subway Station",
	"Radar",
	"Water tower",
	"Bus station",
	"Rail station",
	"Parking lot",
	"Parking lot",
	"Loading bay",
	"Top Secret",
	"Cargo yard",
	"man",
	"Water treatment plant",
	"Library",
	"Hangar",
	"Church",
	"Marina",
	"Missile silo",
	"Desalinization plant",
	"Plymoth Archology",
	"Forest Arcology",
	"Darco Arcology",
	"Lanch Archology",
	"Braun Llama-dome",
]
const CLEAR_TERRAIN := "Clear terrain"
const FRESH_WATER := "Fresh water"
const SALT_WATER := "Salt water"
const SAILBOAT := "First Light (Capt. J. Scirica)"
const SPORTS: Array[String] = ["Football", "Baseball", "Soccer", "Cricket", "Rugby"]
const ACTIONS := {"city_analysis": "Analyze", "library_ruminate": "Ruminate"}

# information lines for each xmic type
const MICROSIM_LINES := [
	[],
	[
		"Max. Output : #1 MWatts",
		"Running at #2% of Capacity",
		"Age(Max) : #0 yrs (50)",
	],
	[
		"Employees : #1",
		"Built in : #2",
	],
	[
		"Beds : 1000",
		"Patients : #1",
		"Doctors : #2",
		"Grade : #G",
		"Annual Cost : $#3",
	],
	[
		"Officers : #1",
		"Crimes Reported : #2",
		"Arrests : #3",
		"Annual Cost : $#0",
	],
	[
		"Firefighters : #1",
		"Fire Engines : #2",
		"Response Time : #3 minutes",
		"Annual Cost : $#0",
	],
	[
		"Capacity : 1500",
		"Students : #1",
		"Teachers : #2",
		"Grade : #G",
		"Annual Cost : $#3",
	],
	[
		"Capacity : 25000",
		"Attendance : #1",
		"Local Team : #S",
		"#T",
		"Wins-Losses : #W",
	],
	[
		"Capacity : 10000",
		"Inmates : #1",
		"Guards : #2",
		"Escapes : #0",
		"% of Capacity : #3",
	],
	[
		"Capacity : 5000",
		"Attendance : #1",
		"Teachers : #2",
		"Grade : #G",
		"Annual Cost : $#3",
	],
	[
		"Peruvian LLamas : #1",
		"Andean LLamas : #2",
		"Alpacas : #3",
		"Other Dromedaries : #0",
	],
	[
		"Height : 65 feet",
		"Material : Bronze",
		"Built in : #1",
		"Pigeons perched : #2",
	],
	[
		"Approval Rating : #2%",
		"Built in : #1",
		"Employees : #3",
		"Doorstops : #0",
	],
	[
		"Capacity : 5,000 cubic feet/minute",
		"Untreated filth : #1,000 cubic feet",
		"Treated filth : #2,000 cubic feet",
	],
	[
		"Running at #0% of Capacity",
		"salt/tons removed : #1 ",
		"Employees : #2",
		"Conditions : #G",
	],
	[
		"Design Capacity : #1000",
		"Residents : #2",
		"Built in : #3",
		"Conditions : #G",
	],
	[
		"Weddings : #0",
		"Visitors : #1",
		"Llama Sightings : #2",
		"Complaints : #3",
		"Bungee Jumps : #0",
	],
	[
		"Bus Stations   : #1",
		"Buses          : #2",
		"Passengers/day  : #3",
		"(statistics are for ",
		" citywide bus system)",
	],
	[
		"Rail Stations  : #1",
		"Passengers/day  : #3",
		"(statistics are for ",
		" citywide rail system)",
	],
	[
		"Subway Stations : #1",
		"Passengers/day  : #3",
		"(statistics are for ",
		" citywide subway system)",
	],
	[
		"Wind generators : #1",
		"Max. system Output : #2 MWatts",
		"(statistics are for citywide",
		" wind power system)",
	],
	[
		"Hydro generators : #1",
		"Max. system Output : #2 MWatts",
		"(statistics are for citywide",
		" hydroelectric system)",
	],
	[
		"Attendance : #1 (last year)",
		"Acres : #2 (citywide)",
		"Employees : #3",
		"(statistics are for ",
		" citywide park system)",
	],
	[
		"Attendance : #1 (last year)",
		"Exhibits   : #2",
		"(statistics are total",
		" for all city museums)",
	],
	[
		"Attendance : #1",
		"Books : #2",
		"Grade : #G",
		"(statistics are total",
		" for all city libraries)",
	],
	[
		"Boats : #1",
		"(statistics are total",
		" for all city marinas)",
	],
]


static func tile_name(tile_id: int) -> String:
	if tile_id == Tiles.EMPTY:
		return CLEAR_TERRAIN
	if tile_id < Tiles.EMPTY or tile_id > Tiles.LLAMA_DOME:
		return ""
	if tile_id >= Tiles.COMMERCIAL_1X1_FIRST:
		return TILE_NAMES[tile_id - 0x66]
	for index in GENERAL_NAME_UPPER_BOUNDS.size():
		if tile_id < GENERAL_NAME_UPPER_BOUNDS[index]:
			return TILE_NAMES[index]
	return ""
