class_name OrdinanceIds
extends RefCounted
## Ordinance positions in the saved MISC flags.

enum Id {
	SALES_TAX,
	INCOME_TAX,
	LEGALIZED_GAMBLING,
	PARKING_FINES,
	VOLUNTEER_FIRE,
	PUBLIC_SMOKING_BAN,
	FREE_CLINICS,
	JUNIOR_SPORTS,
	PRO_READING,
	ANTI_DRUG,
	CPR_TRAINING,
	NEIGHBORHOOD_WATCH,
	TOURIST_ADVERTISING,
	BUSINESS_ADVERTISING,
	CITY_BEAUTIFICATION,
	ANNUAL_CARNIVAL,
	ENERGY_CONSERVATION,
	NUCLEAR_FREE_ZONE,
	HOMELESS_SHELTER,
	POLLUTION_CONTROLS,
}

const COUNT := Id.POLLUTION_CONTROLS + 1
const SALES_TAX_MASK := 1 << Id.SALES_TAX
const INCOME_TAX_MASK := 1 << Id.INCOME_TAX
const LEGALIZED_GAMBLING_MASK := 1 << Id.LEGALIZED_GAMBLING
const PARKING_FINES_MASK := 1 << Id.PARKING_FINES
const VOLUNTEER_FIRE_MASK := 1 << Id.VOLUNTEER_FIRE
const PUBLIC_SMOKING_BAN_MASK := 1 << Id.PUBLIC_SMOKING_BAN
const FREE_CLINICS_MASK := 1 << Id.FREE_CLINICS
const JUNIOR_SPORTS_MASK := 1 << Id.JUNIOR_SPORTS
const PRO_READING_MASK := 1 << Id.PRO_READING
const ANTI_DRUG_MASK := 1 << Id.ANTI_DRUG
const CPR_TRAINING_MASK := 1 << Id.CPR_TRAINING
const NEIGHBORHOOD_WATCH_MASK := 1 << Id.NEIGHBORHOOD_WATCH
const TOURIST_ADVERTISING_MASK := 1 << Id.TOURIST_ADVERTISING
const BUSINESS_ADVERTISING_MASK := 1 << Id.BUSINESS_ADVERTISING
const CITY_BEAUTIFICATION_MASK := 1 << Id.CITY_BEAUTIFICATION
const ANNUAL_CARNIVAL_MASK := 1 << Id.ANNUAL_CARNIVAL
const ENERGY_CONSERVATION_MASK := 1 << Id.ENERGY_CONSERVATION
const NUCLEAR_FREE_ZONE_MASK := 1 << Id.NUCLEAR_FREE_ZONE
const HOMELESS_SHELTER_MASK := 1 << Id.HOMELESS_SHELTER
const POLLUTION_CONTROLS_MASK := 1 << Id.POLLUTION_CONTROLS
