class_name PollutionConstants
extends RefCounted

const Tiles = preload("res://src/tools/shared/building_tile_ids.gd")

const MAP_SIZE := 64
const SERVICE_MAP_SIZE := 32
const FULL_MAP_SIZE := CityState.MAP_SIZE
const VALUE_COUNT := MAP_SIZE * MAP_SIZE
const MISC_CITY_POLLUTION := 0x0034
const MISC_CITY_LAND_VALUE := 0x0028
const MISC_CITY_CRIME := 0x002c
const MISC_BUDGETS := 0x077c
const MISC_BUDGET_RECORD_SIZE := 0x006c
const MISC_ORDINANCES := 0x0fa0
const MISC_CITY_CENTER_X := 0x1018
const MISC_CITY_CENTER_Y := 0x101c
const MISC_POLLUTION_BONUS := 0x1034
const MISC_PRISON_BONUS := 0x103c
const MISC_TREATMENT_SUFFICIENT := 0x104c
const CLEAN_INDUSTRY_ORDINANCE := 0x00080000
const POLICE_COVERAGE_ORDINANCE := 0x00000800
const FIRE_COVERAGE_ORDINANCE := 0x00000010
const CRIME_REDUCTION_ORDINANCE := 0x00000004
const RADIOACTIVITY := Tiles.RADIOACTIVE_WASTE
const FIRST_TREE := Tiles.TREE_FIRST
const SMALL_PARK := Tiles.SMALL_PARK
const FIRST_ROAD := Tiles.FIRST_ROAD
const FIRST_POLLUTING_BUILDING := Tiles.DEVELOPED_FIRST
const BIG_PARK := Tiles.BIG_PARK
const POLICE_STATION := Tiles.POLICE_STATION
const FIRE_STATION := Tiles.FIRE_STATION
const FIRST_POWER_PLANT := Tiles.HYDRO_POWER_ONE
const FIRST_ARCOLOGY := Tiles.PLYMOUTH_ARCOLOGY
const LAST_ARCOLOGY := Tiles.LAUNCH_ARCOLOGY
const FLAG_WATER := 0x04
const FLAG_MARK := 0x08
const FLAG_WATERED := 0x10
const FLAG_POWERED := 0x40
const ZONE_BUILDING_ORIGIN := 0x80
const BUDGET_POLICE := 5
const BUDGET_FIRE := 6

const LAND_VALUE_HALVED := {
	0x8a: true, 0x8b: true,
	0xaa: true, 0xab: true, 0xac: true, 0xad: true,
	0xc4: true, 0xc5: true,
}

# nonzero bytes from the supplied executable table at 0x004e95b8
const BUILDING_POLLUTION := {
	0x84: 6, 0x85: 6, 0x86: 6, 0x87: 6,
	0x9e: 12, 0x9f: 12, 0xa0: 12, 0xa1: 12,
	0xa2: 18, 0xa3: 18, 0xa4: 18, 0xa5: 18,
	0xbc: 24, 0xbd: 24, 0xbe: 24, 0xbf: 24, 0xc0: 24, 0xc1: 24,
	Tiles.GAS_POWER: 10, Tiles.OIL_POWER: 25, Tiles.NUCLEAR_POWER: 2, Tiles.FUSION_POWER: 2, Tiles.COAL_POWER: 50,
	Tiles.STADIUM: 4, Tiles.PRISON: 10, Tiles.WATER_PUMP: 2, Tiles.RUNWAY: 10, Tiles.RUNWAY_CROSSING: 10, Tiles.PIER: 10,
	Tiles.CRANE: 5, Tiles.SEAPORT_WAREHOUSE: 5, Tiles.AIRPORT_BUILDING_ONE: 5, Tiles.AIRPORT_BUILDING_TWO: 5, Tiles.TARMAC: 10, Tiles.FIGHTER_JET: 10,
	Tiles.SUBWAY_STATION: 5, Tiles.BUS_DEPOT: 3, Tiles.RAIL_STATION: 4, Tiles.PARKING_LOT_ONE: 2, Tiles.PARKING_LOT_TWO: 2, Tiles.LOADING_BAY: 2, Tiles.TOP_SECRET: 2,
	Tiles.CARGO_YARD: 10, Tiles.WATER_TREATMENT: 10, Tiles.HANGAR_TWO: 5, Tiles.PLYMOUTH_ARCOLOGY: 25, Tiles.FOREST_ARCOLOGY: 10, Tiles.DARCO_ARCOLOGY: 12, Tiles.LAUNCH_ARCOLOGY: 15,
}
