max_line_length = 140
use_tabs = true
max_function_length = 100
max_file_length = 2500
max_parameters = 8
max_nesting_depth = 6
exclude = [".godot", "addons"]

[rules]
"format/large-number-underscores" = "off"
