class_name MicrosimAnnualConstants
extends RefCounted

const Tiles = preload("res://src/tools/shared/building_tile_ids.gd")

const MISC_SIZE := Sc2MiscLayout.SIZE
const MISC_CITY_CRIME := Sc2MiscLayout.CITY_CRIME
const MISC_RAW_POPULATION := Sc2MiscLayout.POPULATION_TABLE
const MISC_DEMOGRAPHIC_RECORD_SIZE := 0x000c
const MISC_FUNDS := Sc2MiscLayout.FUNDS
const MISC_TILE_COUNTS := Sc2MiscLayout.TILE_COUNTS
const MISC_BUDGETS := Sc2MiscLayout.BUDGETS
const MISC_AUTO_GOTO := Sc2MiscLayout.AUTO_GOTO
const MISC_NO_DISASTERS := Sc2MiscLayout.NO_DISASTERS
const MISC_ARCOLOGY_POPULATION := Sc2MiscLayout.ARCOLOGY_POPULATION
const MISC_NORMAL_POPULATION := Sc2MiscLayout.NORMAL_POPULATION
const MISC_OLD_ARRESTS := Sc2MiscLayout.OLD_ARRESTS
const MISC_PRISON_BONUS := Sc2MiscLayout.PRISON_BONUS
const BUDGET_RECORD_SIZE := Sc2BudgetLayout.RECORD_SIZE
const BUDGET_FUNDING := Sc2BudgetLayout.FUNDING
const BUDGET_POLICE := Sc2BudgetLayout.POLICE
const BUDGET_FIRE := Sc2BudgetLayout.FIRE
const BUDGET_HEALTH := Sc2BudgetLayout.HEALTH
const BUDGET_SCHOOL := Sc2BudgetLayout.SCHOOL
const BUDGET_COLLEGE := Sc2BudgetLayout.COLLEGE
const POWER_PLANT_COSTS := {
	Tiles.GAS_POWER: 2000,
	Tiles.OIL_POWER: 6600,
	Tiles.NUCLEAR_POWER: 15000,
	Tiles.SOLAR_POWER: 1300,
	Tiles.MICROWAVE_POWER: 28000,
	Tiles.FUSION_POWER: 40000,
	Tiles.COAL_POWER: 4000,
}

const TILE_SMALL_PARK := Tiles.SMALL_PARK
const TILE_HYDRO_ONE := Tiles.HYDRO_POWER_1
const TILE_HYDRO_TWO := Tiles.HYDRO_POWER_2
const TILE_WIND_POWER := Tiles.WIND_POWER
const TILE_POWER_FIRST := Tiles.GAS_POWER
const TILE_POWER_LAST := Tiles.COAL_POWER
const TILE_CITY_HALL := Tiles.CITY_HALL
const TILE_HOSPITAL := Tiles.HOSPITAL
const TILE_POLICE_STATION := Tiles.POLICE_STATION
const TILE_FIRE_STATION := Tiles.FIRE_STATION
const TILE_MUSEUM := Tiles.MUSEUM
const TILE_BIG_PARK := Tiles.BIG_PARK
const TILE_SCHOOL := Tiles.SCHOOL
const TILE_STADIUM := Tiles.STADIUM
const TILE_PRISON := Tiles.PRISON
const TILE_COLLEGE := Tiles.COLLEGE
const TILE_ZOO := Tiles.ZOO
const TILE_STATUE := Tiles.STATUE
const TILE_SUBWAY_STATION := Tiles.SUBWAY_STATION
const TILE_BUS_DEPOT := Tiles.BUS_DEPOT
const TILE_RAIL_STATION := Tiles.RAIL_STATION
const TILE_MAYOR_HOUSE := Tiles.MAYOR_HOUSE
const TILE_WATER_TREATMENT := Tiles.WATER_TREATMENT
const TILE_LIBRARY := Tiles.LIBRARY
const TILE_MARINA := Tiles.MARINA
const TILE_DESALINIZATION := Tiles.DESALINIZATION
const TILE_ARCOLOGY_FIRST := Tiles.PLYMOUTH_ARCOLOGY
const TILE_ARCOLOGY_LAST := Tiles.LAUNCH_ARCOLOGY
const TILE_LAUNCH_ARCOLOGY := Tiles.LAUNCH_ARCOLOGY
const TILE_LLAMADOME := Tiles.LLAMA_DOME
const NEWS_POWER_PLANT := 0x24
const NEWS_PRISON := 0x25
const NEWS_EDUCATION := 0x26
# message box string IDs, not newspaper stories
const NOTICE_ARCOLOGY_LAUNCH_START := 529
const NOTICE_ARCOLOGY_LAUNCH_END := 530
const SOUND_EXPLOSION := 504
