class_name MicrosimAnnualConstants
extends RefCounted

const Tiles = preload("res://src/tools/shared/building_tile_ids.gd")

const MISC_SIZE := 4800
const MISC_CITY_CRIME := 0x002c
const MISC_RAW_POPULATION := 0x007c
const MISC_DEMOGRAPHIC_RECORD_SIZE := 0x000c
const MISC_FUNDS := 0x0014
const MISC_TILE_COUNTS := 0x01f0
const MISC_BUDGETS := 0x077c
const MISC_AUTO_GOTO := 0x0ff4
const MISC_NO_DISASTERS := 0x1000
const MISC_ARCOLOGY_POPULATION := 0x1020
const MISC_NORMAL_POPULATION := 0x102c
const MISC_OLD_ARRESTS := 0x1038
const MISC_PRISON_BONUS := 0x103c
const BUDGET_RECORD_SIZE := 0x006c
const BUDGET_FUNDING := 0x04
const BUDGET_POLICE := 5
const BUDGET_FIRE := 6
const BUDGET_HEALTH := 7
const BUDGET_SCHOOL := 8
const BUDGET_COLLEGE := 9
const POWER_PLANT_COSTS := {
	Tiles.GAS_POWER: 2000,
	Tiles.OIL_POWER: 6600,
	Tiles.NUCLEAR_POWER: 15000,
	Tiles.SOLAR_POWER: 1300,
	Tiles.MICROWAVE_POWER: 28000,
	Tiles.FUSION_POWER: 40000,
	Tiles.COAL_POWER: 4000,
}

const TILE_SMALL_PARK := Tiles.SMALL_PARK
const TILE_HYDRO_ONE := Tiles.HYDRO_POWER_1
const TILE_HYDRO_TWO := Tiles.HYDRO_POWER_2
const TILE_WIND_POWER := Tiles.WIND_POWER
const TILE_POWER_FIRST := Tiles.GAS_POWER
const TILE_POWER_LAST := Tiles.COAL_POWER
const TILE_CITY_HALL := Tiles.CITY_HALL
const TILE_HOSPITAL := Tiles.HOSPITAL
const TILE_POLICE_STATION := Tiles.POLICE_STATION
const TILE_FIRE_STATION := Tiles.FIRE_STATION
const TILE_MUSEUM := Tiles.MUSEUM
const TILE_BIG_PARK := Tiles.BIG_PARK
const TILE_SCHOOL := Tiles.SCHOOL
const TILE_STADIUM := Tiles.STADIUM
const TILE_PRISON := Tiles.PRISON
const TILE_COLLEGE := Tiles.COLLEGE
const TILE_ZOO := Tiles.ZOO
const TILE_STATUE := Tiles.STATUE
const TILE_SUBWAY_STATION := Tiles.SUBWAY_STATION
const TILE_BUS_DEPOT := Tiles.BUS_DEPOT
const TILE_RAIL_STATION := Tiles.RAIL_STATION
const TILE_MAYOR_HOUSE := Tiles.MAYOR_HOUSE
const TILE_WATER_TREATMENT := Tiles.WATER_TREATMENT
const TILE_LIBRARY := Tiles.LIBRARY
const TILE_MARINA := Tiles.MARINA
const TILE_DESALINIZATION := Tiles.DESALINIZATION
const TILE_ARCOLOGY_FIRST := Tiles.PLYMOUTH_ARCOLOGY
const TILE_ARCOLOGY_LAST := Tiles.LAUNCH_ARCOLOGY
const TILE_LAUNCH_ARCOLOGY := Tiles.LAUNCH_ARCOLOGY
const TILE_LLAMADOME := Tiles.LLAMA_DOME
const NEWS_POWER_PLANT := 0x24
const NEWS_EDUCATION := 0x26
const NEWS_ARCOLOGY_LAUNCH_START := 0x211
const NEWS_ARCOLOGY_LAUNCH_END := 0x212
const SOUND_EXPLOSION := 504
