//! The text of the query dialog, as QueryStrings and the name tables of
//! QueryConstants. The spelling follows the executable.

use crate::sim::ids::building_tile_ids as tiles;
use crate::sim::ids::sc2tile_flags as flags;

/// The building ID whose name follows the general names directly.
const FIRST_NAMED_DEVELOPMENT: i64 = 0x66;

/// The first strict upper bound above a building ID selects its name index.
pub const GENERAL_NAME_UPPER_BOUNDS: [i64; 22] = [
    tiles::RUBBLE_FIRST,
    tiles::RADIOACTIVE_WASTE,
    tiles::TREE_FIRST,
    tiles::SMALL_PARK,
    tiles::POWER_LINE_FIRST,
    tiles::FIRST_ROAD,
    tiles::RAIL_FIRST,
    tiles::TUNNEL_FIRST,
    tiles::ROAD_POWER_CROSSING_1,
    tiles::RAIL_POWER_CROSSING_1,
    tiles::HIGHWAY_STRAIGHT_1,
    tiles::SUSPENSION_BRIDGE_1,
    tiles::RAISING_BRIDGE_TOWER,
    tiles::POWER_BRIDGE,
    tiles::ONRAMP_FIRST,
    tiles::HIGHWAY_SLOPE_FIRST,
    tiles::HIGHWAY_BRIDGE,
    tiles::RAIL_SUBWAY_FIRST,
    tiles::DEVELOPED_FIRST,
    tiles::MIDDLE_CLASS_HOMES_1X1_1,
    tiles::LUXURY_HOMES_1X1_1,
    tiles::COMMERCIAL_1X1_FIRST,
];

/// The tile names by name index.
pub const TILE_NAMES: [&str; 154] = [
    "Katzenjammers",
    "Rubble",
    "Radioactive Waste",
    "Trees",
    "Park",
    "Power Lines",
    "Road",
    "Railway",
    "Tunnel Entrance",
    "Road",
    "Railway",
    "Highway",
    "Suspension Bridge",
    "Bridge",
    "Power Lines",
    "Highway Entrance",
    "Highway",
    "Highway Bridge",
    "Subway to Rail",
    "Lower-class homes",
    "Middle-class homes",
    "Luxury Homes",
    "Gas Station",
    "Bed & Breakfast Inn",
    "Convience Store",
    "Gas Station",
    "Small office building",
    "Office building",
    "Warehouse",
    "Cassidy's Toy Store",
    "Warehouse",
    "Chemical Storage",
    "Warehouse",
    "Industrial substation",
    "Construction",
    "Construction",
    "Abandoned building",
    "Abandoned building",
    "Cheap apartments",
    "Apartments",
    "Apartments",
    "Nice Apartments",
    "Nice Apartments",
    "Condominium",
    "Condominium",
    "Condominium",
    "Shopping center",
    "Grocery story",
    "Office building",
    "Resort hotel",
    "Office building",
    "Office / Retail",
    "Office building",
    "Office building",
    "Office building",
    "Office building",
    "Warehouse",
    "Chemical processing",
    "Factory",
    "Factory",
    "Factory",
    "Factory",
    "Factory",
    "Factory",
    "Construction",
    "Construction",
    "Construction",
    "Construction",
    "Abandoned building",
    "Abandoned building",
    "Abandoned building",
    "Abandoned building",
    "Large apartment building",
    "Large apartment building",
    "Condominium",
    "Condominium",
    "Office park",
    "Office tower",
    "Mini-mall",
    "Theatre Square",
    "Drive-in theater",
    "Office tower",
    "Office tower",
    "Parking lot",
    "Historic office building",
    "Corporate headquarters",
    "Chemical processing",
    "Large factory",
    "Industrial thingamajig",
    "Factory",
    "Large warehouse",
    "Warehouse",
    "Construction",
    "Construction",
    "Abandoned building",
    "Abandoned building",
    "Hydroelectric power",
    "Hydroelectric power",
    "Wind power",
    "Natural gas power plant",
    "Oil power plant",
    "Nuclear power plant",
    "Solar power plant",
    "Microwave power plant",
    "Fusion power plant",
    "Coal power plant",
    "City Hall",
    "Hospital",
    "Police station",
    "Fire station",
    "Museum",
    "Park",
    "School",
    "Stadium",
    "Prison",
    "College",
    "Zoo",
    "Statue",
    "Water pump",
    "Runway",
    "Runway",
    "Pier",
    "Crane",
    "Control tower",
    "Control tower",
    "Warehouse",
    "Building",
    "Buiding",
    "Tarmac",
    "F-15b",
    "Hanger",
    "Subway Station",
    "Radar",
    "Water tower",
    "Bus station",
    "Rail station",
    "Parking lot",
    "Parking lot",
    "Loading bay",
    "Top Secret",
    "Cargo yard",
    "man",
    "Water treatment plant",
    "Library",
    "Hangar",
    "Church",
    "Marina",
    "Missile silo",
    "Desalinization plant",
    "Plymoth Archology",
    "Forest Arcology",
    "Darco Arcology",
    "Lanch Archology",
    "Braun Llama-dome",
];

pub const CLEAR_TERRAIN: &str = "Clear terrain";
pub const FRESH_WATER: &str = "Fresh water";
pub const SALT_WATER: &str = "Salt water";
pub const SAILBOAT: &str = "First Light (Capt. J. Scirica)";

pub const SPORTS: [&str; 5] = ["Football", "Baseball", "Soccer", "Cricket", "Rugby"];

/// The information lines of each XMIC type. `#0` to `#3` are the statistics,
/// `#G` a grade, `#S` a sport, `#T` the label of statistic 3, and `#W` wins and losses.
pub const MICROSIM_LINES: [&[&str]; 26] = [
    &[],
    &["Max. Output : #1 MWatts", "Running at #2% of Capacity", "Age(Max) : #0 yrs (50)"],
    &["Employees : #1", "Built in : #2"],
    &["Beds : 1000", "Patients : #1", "Doctors : #2", "Grade : #G", "Annual Cost : $#3"],
    &["Officers : #1", "Crimes Reported : #2", "Arrests : #3", "Annual Cost : $#0"],
    &[
        "Firefighters : #1",
        "Fire Engines : #2",
        "Response Time : #3 minutes",
        "Annual Cost : $#0",
    ],
    &[
        "Capacity : 1500",
        "Students : #1",
        "Teachers : #2",
        "Grade : #G",
        "Annual Cost : $#3",
    ],
    &["Capacity : 25000", "Attendance : #1", "Local Team : #S", "#T", "Wins-Losses : #W"],
    &[
        "Capacity : 10000",
        "Inmates : #1",
        "Guards : #2",
        "Escapes : #0",
        "% of Capacity : #3",
    ],
    &[
        "Capacity : 5000",
        "Attendance : #1",
        "Teachers : #2",
        "Grade : #G",
        "Annual Cost : $#3",
    ],
    &[
        "Peruvian LLamas : #1",
        "Andean LLamas : #2",
        "Alpacas : #3",
        "Other Dromedaries : #0",
    ],
    &["Height : 65 feet", "Material : Bronze", "Built in : #1", "Pigeons perched : #2"],
    &["Approval Rating : #2%", "Built in : #1", "Employees : #3", "Doorstops : #0"],
    &[
        "Capacity : 5,000 cubic feet/minute",
        "Untreated filth : #1,000 cubic feet",
        "Treated filth : #2,000 cubic feet",
    ],
    &[
        "Running at #0% of Capacity",
        "salt/tons removed : #1 ",
        "Employees : #2",
        "Conditions : #G",
    ],
    &["Design Capacity : #1000", "Residents : #2", "Built in : #3", "Conditions : #G"],
    &[
        "Weddings : #0",
        "Visitors : #1",
        "Llama Sightings : #2",
        "Complaints : #3",
        "Bungee Jumps : #0",
    ],
    &[
        "Bus Stations   : #1",
        "Buses          : #2",
        "Passengers/day  : #3",
        "(statistics are for ",
        " citywide bus system)",
    ],
    &[
        "Rail Stations  : #1",
        "Passengers/day  : #3",
        "(statistics are for ",
        " citywide rail system)",
    ],
    &[
        "Subway Stations : #1",
        "Passengers/day  : #3",
        "(statistics are for ",
        " citywide subway system)",
    ],
    &[
        "Wind generators : #1",
        "Max. system Output : #2 MWatts",
        "(statistics are for citywide",
        " wind power system)",
    ],
    &[
        "Hydro generators : #1",
        "Max. system Output : #2 MWatts",
        "(statistics are for citywide",
        " hydroelectric system)",
    ],
    &[
        "Attendance : #1 (last year)",
        "Acres : #2 (citywide)",
        "Employees : #3",
        "(statistics are for ",
        " citywide park system)",
    ],
    &[
        "Attendance : #1 (last year)",
        "Exhibits   : #2",
        "(statistics are total",
        " for all city museums)",
    ],
    &[
        "Attendance : #1",
        "Books : #2",
        "Grade : #G",
        "(statistics are total",
        " for all city libraries)",
    ],
    &["Boats : #1", "(statistics are total", " for all city marinas)"],
];

pub const GRADE_NAMES: [&str; 13] = ["F", "D-", "D", "D+", "C-", "C", "C+", "B-", "B", "B+", "A-", "A", "A+"];

/// The executable names unused zones 10 and 11 as Seaport and Airport.
pub const ZONE_NAMES: [&str; 12] = [
    "Unzoned",
    "Residential",
    "Residential",
    "Commercial",
    "Commercial",
    "Industrial",
    "Industrial",
    "Military",
    "Airport",
    "Seaport",
    "Seaport",
    "Airport",
];

pub const ZONE_DENSITIES: [&str; 10] = [
    "",
    "low-density",
    "high-density",
    "low-density",
    "high-density",
    "low-density",
    "high-density",
    "",
    "",
    "",
];

pub const UNDERGROUND_NAMES: [&str; 36] = [
    "None",
    "Subway (LR)",
    "Subway (TB)",
    "Subway (HTB)",
    "Subway (LHR)",
    "Subway (THB)",
    "Subway (HLR)",
    "Subway (BR)",
    "Subway (BL)",
    "Subway (TL)",
    "Subway (TR)",
    "Subway (RTB)",
    "Subway (LBR)",
    "Subway (TLB)",
    "Subway (LTR)",
    "Subway (LTBR)",
    "Pipes (LR)",
    "Pipes (TB)",
    "Pipes (HTB)",
    "Pipes (LHR)",
    "Pipes (THB)",
    "Pipes (HLR)",
    "Pipes (BR)",
    "Pipes (BL)",
    "Pipes (TL)",
    "Pipes (TR)",
    "Pipes (RTB)",
    "Pipes (LBR)",
    "Pipes (TLB)",
    "Pipes (LTR)",
    "Pipes (LTBR)",
    "Crossover (PIPESTB_SUBWAYLR)",
    "Crossover (PIPESLR_SUBWAYTB)",
    "Unknown",
    "Missile Silo",
    "Subway Entrance",
];

pub const THING_NAMES: [&str; 17] = [
    "None",
    "Airplane",
    "Helicopter",
    "Cargo ship",
    "Bulldozer",
    "Monster",
    "Explosion",
    "Police",
    "Fire",
    "Sailboat",
    "Train engine",
    "Train car",
    "Subway engine",
    "Subway car",
    "Military",
    "Tornado",
    "Maxis Man",
];

pub const DIRECTION_NAMES: [&str; 8] = ["North", "Northeast", "East", "Southeast", "South", "Southwest", "West", "Northwest"];

pub const FLAG_LABELS: [(i64, &str); 8] = [
    (flags::POWERABLE, "powerable"),
    (flags::POWERED, "powered"),
    (flags::PIPED, "piped"),
    (flags::WATERED, "watered"),
    (flags::MARK, "xvalmask"),
    (flags::WATER, "water"),
    (flags::FLIPPED, "rotated"),
    (flags::SALT_WATER, "saltwater"),
];

/// The name of a building ID. An empty tile is clear terrain.
pub fn tile_name(tile_id: i64) -> &'static str {
    if tile_id == tiles::EMPTY {
        return CLEAR_TERRAIN;
    }

    if !(tiles::EMPTY..=tiles::LLAMA_DOME).contains(&tile_id) {
        return "";
    }

    if tile_id >= tiles::COMMERCIAL_1X1_FIRST {
        return TILE_NAMES[(tile_id - FIRST_NAMED_DEVELOPMENT) as usize];
    }

    match GENERAL_NAME_UPPER_BOUNDS.iter().position(|&bound| tile_id < bound) {
        Some(index) => TILE_NAMES[index],
        None => "",
    }
}
