import { data } from '../data';

export function XTXT(bytes: Buffer) {
  bytes.forEach((bits: any, i: any) => {
    const xtxt: any = {};

    xtxt.data = bits;
    xtxt.type = types[bits].type;
    xtxt.label = types[bits].label;

    if (xtxt.type == 'sign') {
      xtxt.sign = data.segments.XLAB[bits];
    }

    if (xtxt.type == 'microsim') {
      xtxt.microsim = {};
      xtxt.microsim.id = bits - 51;
      xtxt.microsim.label = data.segments.XLAB[bits];

      const xmic = data.segments.XMIC[xtxt.microsim.id];

      if (xmic !== undefined) {
        xtxt.microsim.building = xmic.building;
        xtxt.microsim.data1 = xmic.data1;
        xtxt.microsim.data2 = xmic.data2;
        xtxt.microsim.data3 = xmic.data3;
        xtxt.microsim.data4 = xmic.data4;
      }
    }

    if (xtxt.type == 'disaster') {
      xtxt.disaster = true;
    } else {
      xtxt.disaster = true;
    }

    data.cells[i].segments.XTXT = xtxt;
  });
}

const types = {
  0x00: { type: null, label: null, reference: null },
  0x01: { type: 'sign', label: 'Sign 0', reference: 'XLAB' },
  0x02: { type: 'sign', label: 'Sign 1', reference: 'XLAB' },
  0x03: { type: 'sign', label: 'Sign 2', reference: 'XLAB' },
  0x04: { type: 'sign', label: 'Sign 3', reference: 'XLAB' },
  0x05: { type: 'sign', label: 'Sign 4', reference: 'XLAB' },
  0x06: { type: 'sign', label: 'Sign 5', reference: 'XLAB' },
  0x07: { type: 'sign', label: 'Sign 6', reference: 'XLAB' },
  0x08: { type: 'sign', label: 'Sign 7', reference: 'XLAB' },
  0x09: { type: 'sign', label: 'Sign 8', reference: 'XLAB' },
  0x0a: { type: 'sign', label: 'Sign 9', reference: 'XLAB' },
  0x0b: { type: 'sign', label: 'Sign 10', reference: 'XLAB' },
  0x0c: { type: 'sign', label: 'Sign 11', reference: 'XLAB' },
  0x0d: { type: 'sign', label: 'Sign 12', reference: 'XLAB' },
  0x0e: { type: 'sign', label: 'Sign 13', reference: 'XLAB' },
  0x0f: { type: 'sign', label: 'Sign 14', reference: 'XLAB' },
  0x10: { type: 'sign', label: 'Sign 15', reference: 'XLAB' },
  0x11: { type: 'sign', label: 'Sign 16', reference: 'XLAB' },
  0x12: { type: 'sign', label: 'Sign 17', reference: 'XLAB' },
  0x13: { type: 'sign', label: 'Sign 18', reference: 'XLAB' },
  0x14: { type: 'sign', label: 'Sign 19', reference: 'XLAB' },
  0x15: { type: 'sign', label: 'Sign 20', reference: 'XLAB' },
  0x16: { type: 'sign', label: 'Sign 21', reference: 'XLAB' },
  0x17: { type: 'sign', label: 'Sign 22', reference: 'XLAB' },
  0x18: { type: 'sign', label: 'Sign 23', reference: 'XLAB' },
  0x19: { type: 'sign', label: 'Sign 24', reference: 'XLAB' },
  0x1a: { type: 'sign', label: 'Sign 25', reference: 'XLAB' },
  0x1b: { type: 'sign', label: 'Sign 26', reference: 'XLAB' },
  0x1c: { type: 'sign', label: 'Sign 27', reference: 'XLAB' },
  0x1d: { type: 'sign', label: 'Sign 28', reference: 'XLAB' },
  0x1e: { type: 'sign', label: 'Sign 29', reference: 'XLAB' },
  0x1f: { type: 'sign', label: 'Sign 30', reference: 'XLAB' },
  0x20: { type: 'sign', label: 'Sign 31', reference: 'XLAB' },
  0x21: { type: 'sign', label: 'Sign 32', reference: 'XLAB' },
  0x22: { type: 'sign', label: 'Sign 33', reference: 'XLAB' },
  0x23: { type: 'sign', label: 'Sign 34', reference: 'XLAB' },
  0x24: { type: 'sign', label: 'Sign 35', reference: 'XLAB' },
  0x25: { type: 'sign', label: 'Sign 36', reference: 'XLAB' },
  0x26: { type: 'sign', label: 'Sign 37', reference: 'XLAB' },
  0x27: { type: 'sign', label: 'Sign 38', reference: 'XLAB' },
  0x28: { type: 'sign', label: 'Sign 39', reference: 'XLAB' },
  0x29: { type: 'sign', label: 'Sign 40', reference: 'XLAB' },
  0x2a: { type: 'sign', label: 'Sign 41', reference: 'XLAB' },
  0x2b: { type: 'sign', label: 'Sign 42', reference: 'XLAB' },
  0x2c: { type: 'sign', label: 'Sign 43', reference: 'XLAB' },
  0x2d: { type: 'sign', label: 'Sign 44', reference: 'XLAB' },
  0x2e: { type: 'sign', label: 'Sign 45', reference: 'XLAB' },
  0x2f: { type: 'sign', label: 'Sign 46', reference: 'XLAB' },
  0x30: { type: 'sign', label: 'Sign 47', reference: 'XLAB' },
  0x31: { type: 'sign', label: 'Sign 48', reference: 'XLAB' },
  0x32: { type: 'sign', label: 'Sign 49', reference: 'XLAB' },
  0x33: { type: 'microsim', label: 'Unknown Microsimulator 0', reference: 'XMIC' },
  0x34: { type: 'microsim', label: 'Bus System Microsimulator 1', reference: 'XMIC' },
  0x35: { type: 'microsim', label: 'Rail System Microsimulator 2', reference: 'XMIC' },
  0x36: { type: 'microsim', label: 'Subway System Microsimulator 3', reference: 'XMIC' },
  0x37: { type: 'microsim', label: 'Wind Power Microsimulator 4', reference: 'XMIC' },
  0x38: { type: 'microsim', label: 'Hydro Power Microsimulator 5', reference: 'XMIC' },
  0x39: { type: 'microsim', label: 'Park System Microsimulator 6', reference: 'XMIC' },
  0x3a: { type: 'microsim', label: 'Museum System Microsimulator 7', reference: 'XMIC' },
  0x3b: { type: 'microsim', label: 'Library System Microsimulator 8', reference: 'XMIC' },
  0x3c: { type: 'microsim', label: 'Marina System Microsimulator 9', reference: 'XMIC' },
  0x3d: { type: 'microsim', label: 'Microsimulator 10', reference: 'XMIC' },
  0x3e: { type: 'microsim', label: 'Microsimulator 11', reference: 'XMIC' },
  0x3f: { type: 'microsim', label: 'Microsimulator 12', reference: 'XMIC' },
  0x40: { type: 'microsim', label: 'Microsimulator 13', reference: 'XMIC' },
  0x41: { type: 'microsim', label: 'Microsimulator 14', reference: 'XMIC' },
  0x42: { type: 'microsim', label: 'Microsimulator 15', reference: 'XMIC' },
  0x43: { type: 'microsim', label: 'Microsimulator 16', reference: 'XMIC' },
  0x44: { type: 'microsim', label: 'Microsimulator 17', reference: 'XMIC' },
  0x45: { type: 'microsim', label: 'Microsimulator 18', reference: 'XMIC' },
  0x46: { type: 'microsim', label: 'Microsimulator 19', reference: 'XMIC' },
  0x47: { type: 'microsim', label: 'Microsimulator 20', reference: 'XMIC' },
  0x48: { type: 'microsim', label: 'Microsimulator 21', reference: 'XMIC' },
  0x49: { type: 'microsim', label: 'Microsimulator 22', reference: 'XMIC' },
  0x4a: { type: 'microsim', label: 'Microsimulator 23', reference: 'XMIC' },
  0x4b: { type: 'microsim', label: 'Microsimulator 24', reference: 'XMIC' },
  0x4c: { type: 'microsim', label: 'Microsimulator 25', reference: 'XMIC' },
  0x4d: { type: 'microsim', label: 'Microsimulator 26', reference: 'XMIC' },
  0x4e: { type: 'microsim', label: 'Microsimulator 27', reference: 'XMIC' },
  0x4f: { type: 'microsim', label: 'Microsimulator 28', reference: 'XMIC' },
  0x50: { type: 'microsim', label: 'Microsimulator 29', reference: 'XMIC' },
  0x51: { type: 'microsim', label: 'Microsimulator 30', reference: 'XMIC' },
  0x52: { type: 'microsim', label: 'Microsimulator 31', reference: 'XMIC' },
  0x53: { type: 'microsim', label: 'Microsimulator 32', reference: 'XMIC' },
  0x54: { type: 'microsim', label: 'Microsimulator 33', reference: 'XMIC' },
  0x55: { type: 'microsim', label: 'Microsimulator 34', reference: 'XMIC' },
  0x56: { type: 'microsim', label: 'Microsimulator 35', reference: 'XMIC' },
  0x57: { type: 'microsim', label: 'Microsimulator 36', reference: 'XMIC' },
  0x58: { type: 'microsim', label: 'Microsimulator 37', reference: 'XMIC' },
  0x59: { type: 'microsim', label: 'Microsimulator 38', reference: 'XMIC' },
  0x5a: { type: 'microsim', label: 'Microsimulator 39', reference: 'XMIC' },
  0x5b: { type: 'microsim', label: 'Microsimulator 40', reference: 'XMIC' },
  0x5c: { type: 'microsim', label: 'Microsimulator 41', reference: 'XMIC' },
  0x5d: { type: 'microsim', label: 'Microsimulator 42', reference: 'XMIC' },
  0x5e: { type: 'microsim', label: 'Microsimulator 43', reference: 'XMIC' },
  0x5f: { type: 'microsim', label: 'Microsimulator 44', reference: 'XMIC' },
  0x60: { type: 'microsim', label: 'Microsimulator 45', reference: 'XMIC' },
  0x61: { type: 'microsim', label: 'Microsimulator 46', reference: 'XMIC' },
  0x62: { type: 'microsim', label: 'Microsimulator 47', reference: 'XMIC' },
  0x63: { type: 'microsim', label: 'Microsimulator 48', reference: 'XMIC' },
  0x64: { type: 'microsim', label: 'Microsimulator 49', reference: 'XMIC' },
  0x65: { type: 'microsim', label: 'Microsimulator 50', reference: 'XMIC' },
  0x66: { type: 'microsim', label: 'Microsimulator 51', reference: 'XMIC' },
  0x67: { type: 'microsim', label: 'Microsimulator 52', reference: 'XMIC' },
  0x68: { type: 'microsim', label: 'Microsimulator 53', reference: 'XMIC' },
  0x69: { type: 'microsim', label: 'Microsimulator 54', reference: 'XMIC' },
  0x6a: { type: 'microsim', label: 'Microsimulator 55', reference: 'XMIC' },
  0x6b: { type: 'microsim', label: 'Microsimulator 56', reference: 'XMIC' },
  0x6c: { type: 'microsim', label: 'Microsimulator 57', reference: 'XMIC' },
  0x6d: { type: 'microsim', label: 'Microsimulator 58', reference: 'XMIC' },
  0x6e: { type: 'microsim', label: 'Microsimulator 59', reference: 'XMIC' },
  0x6f: { type: 'microsim', label: 'Microsimulator 60', reference: 'XMIC' },
  0x70: { type: 'microsim', label: 'Microsimulator 61', reference: 'XMIC' },
  0x71: { type: 'microsim', label: 'Microsimulator 62', reference: 'XMIC' },
  0x72: { type: 'microsim', label: 'Microsimulator 63', reference: 'XMIC' },
  0x73: { type: 'microsim', label: 'Microsimulator 64', reference: 'XMIC' },
  0x74: { type: 'microsim', label: 'Microsimulator 65', reference: 'XMIC' },
  0x75: { type: 'microsim', label: 'Microsimulator 66', reference: 'XMIC' },
  0x76: { type: 'microsim', label: 'Microsimulator 67', reference: 'XMIC' },
  0x77: { type: 'microsim', label: 'Microsimulator 68', reference: 'XMIC' },
  0x78: { type: 'microsim', label: 'Microsimulator 69', reference: 'XMIC' },
  0x79: { type: 'microsim', label: 'Microsimulator 70', reference: 'XMIC' },
  0x7a: { type: 'microsim', label: 'Microsimulator 71', reference: 'XMIC' },
  0x7b: { type: 'microsim', label: 'Microsimulator 72', reference: 'XMIC' },
  0x7c: { type: 'microsim', label: 'Microsimulator 73', reference: 'XMIC' },
  0x7d: { type: 'microsim', label: 'Microsimulator 74', reference: 'XMIC' },
  0x7e: { type: 'microsim', label: 'Microsimulator 75', reference: 'XMIC' },
  0x7f: { type: 'microsim', label: 'Microsimulator 76', reference: 'XMIC' },
  0x80: { type: 'microsim', label: 'Microsimulator 77', reference: 'XMIC' },
  0x81: { type: 'microsim', label: 'Microsimulator 78', reference: 'XMIC' },
  0x82: { type: 'microsim', label: 'Microsimulator 79', reference: 'XMIC' },
  0x83: { type: 'microsim', label: 'Microsimulator 80', reference: 'XMIC' },
  0x84: { type: 'microsim', label: 'Microsimulator 81', reference: 'XMIC' },
  0x85: { type: 'microsim', label: 'Microsimulator 82', reference: 'XMIC' },
  0x86: { type: 'microsim', label: 'Microsimulator 83', reference: 'XMIC' },
  0x87: { type: 'microsim', label: 'Microsimulator 84', reference: 'XMIC' },
  0x88: { type: 'microsim', label: 'Microsimulator 85', reference: 'XMIC' },
  0x89: { type: 'microsim', label: 'Microsimulator 86', reference: 'XMIC' },
  0x8a: { type: 'microsim', label: 'Microsimulator 87', reference: 'XMIC' },
  0x8b: { type: 'microsim', label: 'Microsimulator 88', reference: 'XMIC' },
  0x8c: { type: 'microsim', label: 'Microsimulator 89', reference: 'XMIC' },
  0x8d: { type: 'microsim', label: 'Microsimulator 90', reference: 'XMIC' },
  0x8e: { type: 'microsim', label: 'Microsimulator 91', reference: 'XMIC' },
  0x8f: { type: 'microsim', label: 'Microsimulator 92', reference: 'XMIC' },
  0x90: { type: 'microsim', label: 'Microsimulator 93', reference: 'XMIC' },
  0x91: { type: 'microsim', label: 'Microsimulator 94', reference: 'XMIC' },
  0x92: { type: 'microsim', label: 'Microsimulator 95', reference: 'XMIC' },
  0x93: { type: 'microsim', label: 'Microsimulator 96', reference: 'XMIC' },
  0x94: { type: 'microsim', label: 'Microsimulator 97', reference: 'XMIC' },
  0x95: { type: 'microsim', label: 'Microsimulator 98', reference: 'XMIC' },
  0x96: { type: 'microsim', label: 'Microsimulator 99', reference: 'XMIC' },
  0x97: { type: 'microsim', label: 'Microsimulator 100', reference: 'XMIC' },
  0x98: { type: 'microsim', label: 'Microsimulator 101', reference: 'XMIC' },
  0x99: { type: 'microsim', label: 'Microsimulator 102', reference: 'XMIC' },
  0x9a: { type: 'microsim', label: 'Microsimulator 103', reference: 'XMIC' },
  0x9b: { type: 'microsim', label: 'Microsimulator 104', reference: 'XMIC' },
  0x9c: { type: 'microsim', label: 'Microsimulator 105', reference: 'XMIC' },
  0x9d: { type: 'microsim', label: 'Microsimulator 106', reference: 'XMIC' },
  0x9e: { type: 'microsim', label: 'Microsimulator 107', reference: 'XMIC' },
  0x9f: { type: 'microsim', label: 'Microsimulator 108', reference: 'XMIC' },
  0xa0: { type: 'microsim', label: 'Microsimulator 109', reference: 'XMIC' },
  0xa1: { type: 'microsim', label: 'Microsimulator 110', reference: 'XMIC' },
  0xa2: { type: 'microsim', label: 'Microsimulator 111', reference: 'XMIC' },
  0xa3: { type: 'microsim', label: 'Microsimulator 112', reference: 'XMIC' },
  0xa4: { type: 'microsim', label: 'Microsimulator 113', reference: 'XMIC' },
  0xa5: { type: 'microsim', label: 'Microsimulator 114', reference: 'XMIC' },
  0xa6: { type: 'microsim', label: 'Microsimulator 115', reference: 'XMIC' },
  0xa7: { type: 'microsim', label: 'Microsimulator 116', reference: 'XMIC' },
  0xa8: { type: 'microsim', label: 'Microsimulator 117', reference: 'XMIC' },
  0xa9: { type: 'microsim', label: 'Microsimulator 118', reference: 'XMIC' },
  0xaa: { type: 'microsim', label: 'Microsimulator 119', reference: 'XMIC' },
  0xab: { type: 'microsim', label: 'Microsimulator 120', reference: 'XMIC' },
  0xac: { type: 'microsim', label: 'Microsimulator 121', reference: 'XMIC' },
  0xad: { type: 'microsim', label: 'Microsimulator 122', reference: 'XMIC' },
  0xae: { type: 'microsim', label: 'Microsimulator 123', reference: 'XMIC' },
  0xaf: { type: 'microsim', label: 'Microsimulator 124', reference: 'XMIC' },
  0xb0: { type: 'microsim', label: 'Microsimulator 125', reference: 'XMIC' },
  0xb1: { type: 'microsim', label: 'Microsimulator 126', reference: 'XMIC' },
  0xb2: { type: 'microsim', label: 'Microsimulator 127', reference: 'XMIC' },
  0xb3: { type: 'microsim', label: 'Microsimulator 128', reference: 'XMIC' },
  0xb4: { type: 'microsim', label: 'Microsimulator 129', reference: 'XMIC' },
  0xb5: { type: 'microsim', label: 'Microsimulator 130', reference: 'XMIC' },
  0xb6: { type: 'microsim', label: 'Microsimulator 131', reference: 'XMIC' },
  0xb7: { type: 'microsim', label: 'Microsimulator 132', reference: 'XMIC' },
  0xb8: { type: 'microsim', label: 'Microsimulator 133', reference: 'XMIC' },
  0xb9: { type: 'microsim', label: 'Microsimulator 134', reference: 'XMIC' },
  0xba: { type: 'microsim', label: 'Microsimulator 135', reference: 'XMIC' },
  0xbb: { type: 'microsim', label: 'Microsimulator 136', reference: 'XMIC' },
  0xbc: { type: 'microsim', label: 'Microsimulator 137', reference: 'XMIC' },
  0xbd: { type: 'microsim', label: 'Microsimulator 138', reference: 'XMIC' },
  0xbe: { type: 'microsim', label: 'Microsimulator 139', reference: 'XMIC' },
  0xbf: { type: 'microsim', label: 'Microsimulator 140', reference: 'XMIC' },
  0xc0: { type: 'microsim', label: 'Microsimulator 141', reference: 'XMIC' },
  0xc1: { type: 'microsim', label: 'Microsimulator 142', reference: 'XMIC' },
  0xc2: { type: 'microsim', label: 'Microsimulator 143', reference: 'XMIC' },
  0xc3: { type: 'microsim', label: 'Microsimulator 144', reference: 'XMIC' },
  0xc4: { type: 'microsim', label: 'Microsimulator 145', reference: 'XMIC' },
  0xc5: { type: 'microsim', label: 'Microsimulator 146', reference: 'XMIC' },
  0xc6: { type: 'microsim', label: 'Microsimulator 147', reference: 'XMIC' },
  0xc7: { type: 'microsim', label: 'Microsimulator 148', reference: 'XMIC' },
  0xc8: { type: 'microsim', label: 'Microsimulator 149', reference: 'XMIC' },
  0xc9: { type: 'actor', label: 'Actor 0', reference: 'XTHG' },
  0xca: { type: 'actor', label: 'Actor 1', reference: 'XTHG' },
  0xcb: { type: 'actor', label: 'Actor 2', reference: 'XTHG' },
  0xcc: { type: 'actor', label: 'Actor 3', reference: 'XTHG' },
  0xcd: { type: 'actor', label: 'Actor 4', reference: 'XTHG' },
  0xce: { type: 'actor', label: 'Actor 5', reference: 'XTHG' },
  0xcf: { type: 'actor', label: 'Actor 6', reference: 'XTHG' },
  0xd0: { type: 'actor', label: 'Actor 7', reference: 'XTHG' },
  0xd1: { type: 'actor', label: 'Actor 8', reference: 'XTHG' },
  0xd2: { type: 'actor', label: 'Actor 9', reference: 'XTHG' },
  0xd3: { type: 'actor', label: 'Actor 10', reference: 'XTHG' },
  0xd4: { type: 'actor', label: 'Actor 11', reference: 'XTHG' },
  0xd5: { type: 'actor', label: 'Actor 12', reference: 'XTHG' },
  0xd6: { type: 'actor', label: 'Actor 13', reference: 'XTHG' },
  0xd7: { type: 'actor', label: 'Actor 14', reference: 'XTHG' },
  0xd8: { type: 'actor', label: 'Actor 15', reference: 'XTHG' },
  0xd9: { type: 'actor', label: 'Actor 16', reference: 'XTHG' },
  0xda: { type: 'actor', label: 'Actor 17', reference: 'XTHG' },
  0xdb: { type: 'actor', label: 'Actor 18', reference: 'XTHG' },
  0xdc: { type: 'actor', label: 'Actor 19', reference: 'XTHG' },
  0xdd: { type: 'actor', label: 'Actor 20', reference: 'XTHG' },
  0xde: { type: 'actor', label: 'Actor 21', reference: 'XTHG' },
  0xdf: { type: 'actor', label: 'Actor 22', reference: 'XTHG' },
  0xe0: { type: 'actor', label: 'Actor 23', reference: 'XTHG' },
  0xe1: { type: 'actor', label: 'Actor 24', reference: 'XTHG' },
  0xe2: { type: 'actor', label: 'Actor 25', reference: 'XTHG' },
  0xe3: { type: 'actor', label: 'Actor 26', reference: 'XTHG' },
  0xe4: { type: 'actor', label: 'Actor 27', reference: 'XTHG' },
  0xe5: { type: 'actor', label: 'Actor 28', reference: 'XTHG' },
  0xe6: { type: 'actor', label: 'Actor 29', reference: 'XTHG' },
  0xe7: { type: 'actor', label: 'Actor 30', reference: 'XTHG' },
  0xe8: { type: 'actor', label: 'Actor 31', reference: 'XTHG' },
  0xe9: { type: 'actor', label: 'Actor 32', reference: 'XTHG' },
  0xea: { type: 'actor', label: 'Actor 33', reference: 'XTHG' },
  0xeb: { type: 'actor', label: 'Actor 34', reference: 'XTHG' },
  0xec: { type: 'actor', label: 'Actor 35', reference: 'XTHG' },
  0xed: { type: 'actor', label: 'Actor 36', reference: 'XTHG' },
  0xee: { type: 'actor', label: 'Actor 37', reference: 'XTHG' },
  0xef: { type: 'actor', label: 'Actor 38', reference: 'XTHG' },
  0xf0: { type: 'actor', label: 'Actor 39', reference: 'XTHG' },
  0xf1: { type: 'unknown', label: 'Unknown Reference 0 - 0xF1', reference: null },
  0xf2: { type: 'unknown', label: 'Unknown Reference 1 - 0xF2', reference: null },
  0xf3: { type: 'unknown', label: 'Unknown Reference 2 - 0xF3', reference: null },
  0xf4: { type: 'unknown', label: 'Unknown Reference 3 - 0xF4', reference: null },
  0xf5: { type: 'unknown', label: 'Unknown Reference 4 - 0xF5', reference: null },
  0xf6: { type: 'unknown', label: 'Unknown Reference 5 - 0xF6', reference: null },
  0xf7: { type: 'unknown', label: 'Unknown Reference 6 - 0xF7', reference: null },
  0xf8: { type: 'unknown', label: 'Unknown Reference 7 - 0xF8', reference: null },
  0xf9: { type: 'unknown', label: 'Unknown Reference 8 - 0xF9', reference: null },
  0xfa: { type: 'sign', label: 'Neighbor Connection', reference: null },
  0xfb: { type: 'disaster', label: 'Toxic Cloud', reference: 'XTHG' },
  0xfc: { type: 'disaster', label: 'Flood', reference: 'XTHG' },
  0xfd: { type: 'disaster', label: 'Rioters 1', reference: 'XTHG' },
  0xfe: { type: 'disaster', label: 'Rioters 2', reference: 'XTHG' },
  0xff: { type: 'disaster', label: 'Fire', reference: 'XTHG' },
};
