export const data: any = {
  cells: [],
  list: [],
  layers: [],
  sprites: {
    all: [],
    building: [],
    edge: [],
    heightmap: [],
    highway: [],
    pipe: [],
    power: [],
    rail: [],
    road: [],
    subway: [],
    terrain: [],
    underground: [],
    water: [],
    zone: [],
  },
};
