#!/usr/bin/env python3
"""Generate the Unicode mapping from Python's standard Johab (CP1361) codec.

This table contains character mappings only, never supplied game text. A
GDScript constant keeps the mapping in exported games without external codecs.
"""
import json
from pathlib import Path


def main():
    root = Path(__file__).resolve().parents[1]
    output = root / 'game/src/assets/text/johab_table.gd'
    rows = []
    count = 0
    for lead in range(128, 256):
        characters = []
        valid = 0
        for trail in range(256):
            try:
                character = bytes((lead, trail)).decode('johab')
            except UnicodeDecodeError:
                character = '\ufffd'
            if len(character) != 1:
                character = '\ufffd'
            valid += character != '\ufffd'
            characters.append(character)
        if valid:
            rows.append(f'\t{lead}: {json.dumps("".join(characters), ensure_ascii=False)},')
            count += valid
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('extends RefCounted\n'
                      '## Generated by tools/generate_johab_table.py from the standard Johab codec.\n'
                      f'## {count} double-byte mappings; U+FFFD marks an invalid pair.\n\n'
                      'const ROWS: Dictionary[int, String] = {\n'
                      + '\n'.join(rows) + '\n}\n', encoding='utf-8')
    print(f'{output}: {count} mappings in {len(rows)} lead-byte rows')


if __name__ == '__main__':
    main()
