#!/usr/bin/env python3
"""Generate the Unicode mapping from Python's standard Johab (CP1361) codec.

This table contains character mappings only, never supplied game text. A Rust
constant keeps the mapping in exported games without external codecs.
"""
import unicodedata
from pathlib import Path


def rust_literal(text):
    """A Rust string literal of `text`."""
    characters = []
    for character in text:
        if character in '"\\':
            characters.append('\\' + character)
        elif unicodedata.category(character) in ('Cc', 'Cf'):
            characters.append('\\u{%x}' % ord(character))
        else:
            characters.append(character)
    return '"' + ''.join(characters) + '"'


def main():
    root = Path(__file__).resolve().parents[1]
    output = root / 'native/core/assets/src/text/johab_table.rs'
    rows = []
    count = 0
    for lead in range(128, 256):
        characters = []
        valid = 0
        for trail in range(256):
            try:
                character = bytes((lead, trail)).decode('johab')
            except UnicodeDecodeError:
                character = '\ufffd'
            if len(character) != 1:
                character = '\ufffd'
            valid += character != '\ufffd'
            characters.append(character)
        if valid:
            rows.append(f'    ({lead}, {rust_literal("".join(characters))}),')
            count += valid
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('//! Generated by tools/generate_johab_table.py from the standard Johab codec.\n'
                      f'//! {count} double-byte mappings; U+FFFD marks an invalid pair.\n\n'
                      '/// Each lead byte with valid pairs, and the character of each trail byte.\n'
                      '#[rustfmt::skip]\n'
                      f'pub const ROWS: [(u8, &str); {len(rows)}] = [\n'
                      + '\n'.join(rows) + '\n];\n', encoding='utf-8')
    print(f'{output}: {count} mappings in {len(rows)} lead-byte rows')


if __name__ == '__main__':
    main()
