#!/usr/bin/env python3
"""Regenerate each city without references and compare it with the fixed input."""
import os
from pathlib import Path
import tempfile

from validate_project import Project, ROOT, execute, verify_city_fixtures


def main():
    verify_city_fixtures()
    with tempfile.TemporaryDirectory(prefix='city-fixture-determinism-') as folder:
        project = Project(folder)
        try:
            project.configure('generator')
            # Remove only this disposable project's link, never the user's folder.
            reference_link = project.base / 'references'
            if reference_link.is_symlink():
                reference_link.unlink()
            output = Path(folder) / 'generated'
            command = [os.environ.get('GODOT', 'godot'), '--headless', '--audio-driver', 'Dummy',
                       '--path', str(project.path), '--script',
                       'res://tools/build_generated_city_fixtures.gd', '--', f'--output={output}']
            status, _, _ = execute(command, timeout=7200)
            if status != 'PASS':
                raise ValueError('City fixture generation failed')
            source = ROOT / 'game/tests/fixtures/cities'
            for path in sorted(output.iterdir()):
                if path.read_bytes() != (source / path.name).read_bytes():
                    raise ValueError(f'Generated bytes differ: {path.name}. Review and re-baseline explicitly.')
                print('PASS deterministic', path.name)
            # Refusal must happen before any simulation or writes.
            original = {p.name: p.read_bytes() for p in output.iterdir()}
            status, _, content = execute(command, timeout=15)
            if status != 'FAIL' or 'Refuse to overwrite' not in content:
                raise ValueError('Generator did not refuse an existing fixture')
            path = output / 'generated-128.SC2'
            path.write_bytes(path.read_bytes() + b'edited')
            original[path.name] = path.read_bytes()
            status, _, content = execute([*command, '--regenerate'], timeout=15)
            if status != 'FAIL' or 'Refuse to overwrite' not in content:
                raise ValueError('Generator did not protect an edited fixture')
            if {p.name: p.read_bytes() for p in output.iterdir()} != original:
                raise ValueError('Refused generation changed a destination')
            print('PASS existing and edited fixtures remain unchanged')
        finally:
            project.close()
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
