class_name BuildingConstants
extends BuildingTileIds
## Building tool tables. The placement rules run in the native simulation
## library; see native/simulation/src/sim/tools/commands/building.rs.

const MICROSIM_DYNAMIC_FIRST := 10
const MICROSIM_LABEL_BASE := 51
const MISC_STADIUM_TEAMS := Sc2MiscLayout.STADIUM_TEAMS
const STADIUM_TEAM_COUNT := 5
const STADIUM_TEAM_LABEL_BASE := 0xfb
const DEFAULT_STADIUM_TEAM_NAMES := [
	"Llamas",
	"Alpacas",
	"Camels",
	"Dromedaries",
	"Army Ants",
]
const NUISANCE_OBJECTION := "Your citizens urge you to\r\n reconsider the placement\r\nof this facility"
const DEFAULT_MICROSIM_LABELS := {
	HYDRO_POWER_1: "Hydro Power",
	HYDRO_POWER_2: "Hydro Power",
	WIND_POWER: "Wind Power",
	GAS_POWER: "Gas Power",
	OIL_POWER: "Oil Power",
	NUCLEAR_POWER: "Nuclear Power",
	SOLAR_POWER: "Solar Power",
	MICROWAVE_POWER: "Microwave Power",
	FUSION_POWER: "Fusion Power",
	COAL_POWER: "Coal Power",
	CITY_HALL: "City Hall",
	HOSPITAL: "Hospital",
	POLICE_STATION: "Police Station",
	FIRE_STATION: "Fire Station",
	MUSEUM: "Museum",
	BIG_PARK: "SimPark System",
	SCHOOL: "School",
	STADIUM: "Stadium",
	PRISON: "Prison",
	COLLEGE: "College",
	ZOO: "Zoo",
	STATUE: "Statue",
	SUBWAY_STATION: "SimSubway",
	BUS_DEPOT: "SimBus System",
	RAIL_STATION: "SimRail System",
	MAYOR_HOUSE: "Mayor's House",
	WATER_TREATMENT: "Water Treatment",
	LIBRARY: "Library System",
	MARINA: "Marina",
	DESALINIZATION: "Desalinization",
	PLYMOUTH_ARCOLOGY: "Plymouth Arco",
	FOREST_ARCOLOGY: "Forest Arco",
	DARCO_ARCOLOGY: "Darco",
	LAUNCH_ARCOLOGY: "Launch Arco",
	LLAMA_DOME: "Llama Dome",
}
const TILE_BY_TOOL := {
	38: COAL_POWER,
	40: OIL_POWER,
	41: GAS_POWER,
	42: NUCLEAR_POWER,
	43: WIND_POWER,
	44: SOLAR_POWER,
	45: MICROWAVE_POWER,
	46: FUSION_POWER,
	49: WATER_PUMP,
	50: WATER_TOWER,
	51: WATER_TREATMENT,
	52: DESALINIZATION,
	60: MAYOR_HOUSE,
	61: CITY_HALL,
	62: STATUE,
	63: LLAMA_DOME,
	65: PLYMOUTH_ARCOLOGY,
	66: FOREST_ARCOLOGY,
	67: DARCO_ARCOLOGY,
	68: LAUNCH_ARCOLOGY,
	76: BUS_DEPOT,
	86: RAIL_STATION,
	87: SUBWAY_STATION,
	144: SCHOOL,
	145: COLLEGE,
	146: LIBRARY,
	147: MUSEUM,
	156: POLICE_STATION,
	157: FIRE_STATION,
	158: HOSPITAL,
	159: PRISON,
	168: SMALL_PARK,
	169: BIG_PARK,
	170: ZOO,
	171: STADIUM,
	172: MARINA,
}
