extends SceneTree


func _initialize() -> void:
	call_deferred("run")


func run() -> void:
	OS.set_environment("OPENSC2K_GRAPHICS_PACK", ProjectSettings.globalize_path("user://missing-assets"))
	var main = (load("res://main.tscn") as PackedScene).instantiate()
	main.preferences.settings_path = "user://import-runtime-test.cfg"
	root.add_child(main)
	await process_frame
	assert(not main.asset_state.assets_ready)
	OS.set_environment("OPENSC2K_GRAPHICS_PACK", "")
	var folder := ProjectSettings.globalize_path("user://runtime-import-test-%d" % OS.get_process_id())
	var reference := ProjectSettings.globalize_path("res://../references/SIMCITY2000")
	var source_copy := folder.path_join("source")
	assert(OriginalGameInstaller._copy_tree(reference, source_copy).ok)
	var unused := FileAccess.open(source_copy.path_join("unused.txt"), FileAccess.WRITE)
	unused.store_string("Do not retain unrelated source files")
	unused.close()
	var result := OriginalPackImporter.import_executable(source_copy.path_join("SIMCITY.EXE"), folder.path_join("packs"), folder.path_join("saved"))
	assert(result.ok, result.error)
	var media := Sc2MediaImporter.import_assets(source_copy, folder.path_join("media"))
	assert(media.ok and media.failures.is_empty(), media.summary())
	assert(OriginalGameInstaller.remove_tree(source_copy) == OK)
	assert(not DirAccess.dir_exists_absolute(source_copy))
	# moving the imported folder must not break its asset paths
	var imported_root := result.graphics.get_base_dir().get_base_dir()
	var relocated := folder.path_join("relocated")
	assert(DirAccess.rename_absolute(imported_root, relocated) == OK)
	result.graphics = relocated.path_join("graphics/pack.json")
	result.sound = relocated.path_join("sound/pack.json")
	result.music = relocated.path_join("music/pack.json")
	var selected := GameAssetSource.load_source("", "folder", result.graphics)
	assert(selected.error.is_empty(), selected.error)
	assert(selected.has_city_template)
	preload("res://tests/support/imported_asset_checks.gd").check(reference, result.graphics.get_base_dir(), selected.assets)
	preload("res://tests/support/imported_asset_checks.gd").check_invalid(result.graphics.get_base_dir())
	var media_source := GameAssetSource.load_source(source_copy, "folder", media.graphics)
	assert(media_source.error.is_empty() and media_source.has_city_template, media_source.error)
	preload("res://tests/support/imported_asset_checks.gd").check(reference, media.graphics.get_base_dir(), media_source.assets)
	assert(selected.assets.large_sprites.entries.size() == 501)
	assert(MediaPack.load_folder(result.sound, "sound").files.size() == 30)
	assert(MediaPack.load_folder(result.music, "music").files.size() == 19)
	assert(result.cities > 0 and result.scenarios > 0)
	var saved_root := folder.path_join("saved")
	var imported_city := saved_root.path_join("cities/ISLAND.SC2")
	var original_city := ProjectSettings.globalize_path("res://../references/SIMCITY2000/CITIES/ISLAND.SC2")
	assert(FileAccess.get_sha256(imported_city) == FileAccess.get_sha256(original_city))
	var file := FileAccess.open(imported_city, FileAccess.WRITE)
	file.store_string("player save")
	file.close()
	var again := OriginalCityImporter.import_saved_games(ProjectSettings.globalize_path("res://../references/SIMCITY2000"), saved_root)
	assert(again.ok and again.created.size() == 1)
	assert(FileAccess.get_file_as_string(imported_city) == "player save")
	assert(FileAccess.get_sha256(again.created[0]) == FileAccess.get_sha256(original_city))
	var repeated := OriginalCityImporter.import_saved_games(ProjectSettings.globalize_path("res://../references/SIMCITY2000"), saved_root)
	assert(repeated.ok and repeated.created.is_empty())
	main.assets.apply_graphics_source(selected)
	assert(main.asset_state.assets_ready and not main.main_menu.import_button.visible)
	assert(main.audio_controller.set_media_packs(result.sound, result.music))
	assert(main.original_text_resources.newspaper_data != null and main.asset_state.base_large_sprites != null)
	main.new_city.open_new_city_dialog()
	assert(main.city_dialogs.new_city_dialog.visible and not main.new_city_state.session.independent_template)
	main.city_dialogs.new_city_dialog.hide()
	main.scurk_workspace._ensure_scurk_editor()
	assert(main.scurk_editor.pixel_canvas.texture_patterns.size() == ScurkGraphics.TEXTURE_IDS.size())
	main.queue_free()
	await process_frame
	OriginalGameInstaller.remove_tree(folder)
	print("PASS: complete pack import, copied cities, non-overwrite, repeat import and runtime activation")
	quit()
