extends SceneTree
func _initialize() -> void:
	var audio := CityAudioController.new()
	root.add_child(audio)
	audio.setup(ProjectSettings.globalize_path('res://../references'), 0.8, 0.0)
	audio.set_menu_music(true)
	assert(audio.current_track_id == MusicDirector.MAIN_THEME_TRACK)
	audio._on_music_track_finished(MusicDirector.MAIN_THEME_TRACK)
	audio.advance(1)
	assert(audio.music_playback_is_active())
	audio.handle_application_focus_out()
	audio.advance(1)
	assert(audio.music_playback_is_active() and audio.focus_paused)
	audio.handle_application_focus_in(true)
	assert(audio.current_track_id == MusicDirector.MAIN_THEME_TRACK)
	audio.set_menu_music(false)
	assert(not audio.music_playback_is_active())
	audio.set_volumes(0, 0)
	audio.set_menu_music(true)
	audio.advance(1)
	assert(not audio.music_playback_is_active())
	audio.stop_music()
	audio.free()
	print('PASS: menu theme, repeat, focus and mute')
	quit()
